State management feature
Who-put-that-in-my-drive/Moments pull request #25
Opened 2022-10-22 23:15 UTC by patel1643

Added state management library and set up basic skeleton for store

2022-10-24 05:03 UTC, jamestang12 requested changes

2022-10-24 05:04 UTC, jamestang12 commented on client/src/pages/Register.tsx
>                  console.log(res);
My bad I mean line 61

2022-10-24 05:05 UTC, jamestang12 commented on client/src/pages/Register.tsx
>                  console.log(err);
I mean line 66 here

2022-10-24 16:50 UTC, Mwpereira commented on client/src/pages/Login.tsx
> +                        message: 'Wrong password!',
The response errors should either use a msg coming from the server or have a msg based on the error code. Should not check for a string and provide a different msg.

2022-10-24 16:50 UTC, Mwpereira commented on client/src/pages/Login.tsx
> +            .then((res: any) => {
Should try to use async

2022-10-25 03:06 UTC, patel1643 commented on client/src/pages/Login.tsx
> +                        message: 'Wrong password!',
gotcha

2022-10-25 03:07 UTC, patel1643 commented on client/src/pages/Login.tsx
> +                <Text>Login Status: {loggedIn ? 'True => redirect to Dashboard' : 'False'}</Text>
Ohh it's just there for testing at least for now

2022-10-25 03:08 UTC, patel1643 commented on client/src/pages/Login.tsx
> +                if (res.data === 'Signed In') {
yeah will do

2022-10-25 03:08 UTC, patel1643 commented on client/src/pages/Login.tsx
> +                if (err.response.data === 'Incorrect Password') {
@Mwpereira can you confirm this one?

2022-10-25 05:18 UTC, patel1643 commented on client/src/pages/Login.tsx
> +            .then((res: any) => {
gotcha

2022-10-25 05:19 UTC, patel1643 commented on client/src/pages/Login.tsx
> +                        message: 'Wrong password!',
I'll update the code once I get an update from @Mwpereira

2022-10-25 05:29 UTC, closed without merging