added logout and login functionality with user update in store and lo…
Who-put-that-in-my-drive/Moments pull request #40
Opened 2022-11-04 05:37 UTC by patel1643

- added a slide drawer for individual image
- added logout function with backend api call and reroute to login page
- added images functionality
- fixed sidenav
- added userinfo to the store and localstorage

2022-11-04 05:44 UTC, jamestang12 reviewed
Overall LGTM, please remove unnecessary imports and fix Netlify error

2022-11-04 05:44 UTC, jamestang12 commented on client/src/pages/Login.tsx
> +        // console.log(data);
Remove this please

2022-11-04 05:44 UTC, jamestang12 commented on client/src/store/store.tsx
> +// import user from './tempData';
Remove this please

2022-11-04 06:05 UTC, jamestang12 commented
Nice all checks have passed

2022-11-04 06:15 UTC, Mwpereira commented
![image](https://user-images.githubusercontent.com/56651345/199904595-374b92bc-e995-4fe2-9d15-617942c542b7.png)

Should fix this overflow, would be a common bug found for many users

2022-11-04 06:16 UTC, Mwpereira commented
![image](https://user-images.githubusercontent.com/56651345/199904702-4dc56bee-f315-48ce-b966-fade1ee5aff1.png)

What's the difference between documents and photos?

2022-11-04 15:36 UTC, Mwpereira requested changes

2022-11-04 15:36 UTC, Mwpereira commented on client/src/components/PhotoCard.tsx
> +interface PhotoCardProps {
Might be best to add an interfaces folder and add all of the interfaces in there, in case of the event where we need to reuse them

2022-11-04 15:36 UTC, Mwpereira commented on client/src/components/PhotoCard.tsx
> +    imageURL: string
using `,` or `;` after each property would be cool ;)

2022-11-04 15:36 UTC, Mwpereira commented on client/src/components/PhotoCard.tsx
> +interface DrawerImageInfoProps {
Should add this an interfaces folder (as suggested above)

2022-11-04 15:36 UTC, Mwpereira commented on client/src/components/PhotoCard.tsx
> +const DrawerImageInfo = (props: DrawerImageInfoProps) => {
Should this be its own component?

2022-11-04 15:36 UTC, Mwpereira commented on client/src/components/PhotoCard.tsx
> +const DrawerImageInfo = (props: DrawerImageInfoProps) => {
Like in its own components file

2022-11-04 15:36 UTC, Mwpereira commented on client/src/components/SideNavBar.tsx
> +        return await axios.get(URL + '/api/auth/logout');
should create a service / axios helper to configure its proxy/url and other settings associated with it

2022-11-04 15:36 UTC, Mwpereira commented on client/src/pages/Login.tsx
>              const response: any = await login(data.email, data.password);
Here you're expecting a value but the `login` method says it returns `Promise<void>`. Axios has a response type that you can use and leverage in this case

2022-11-04 15:36 UTC, Mwpereira commented on client/src/pages/Login.tsx
> +            if (response) {
May want to validate the response differently

2022-11-04 15:36 UTC, Mwpereira commented on client/src/pages/Login.tsx
> +            if (response) {
Checking the status code is the best option, handling different status codes is the way to go in this case

2022-11-04 15:36 UTC, Mwpereira commented on client/src/pages/Uploads.tsx
> +    const store = useStore();
Should create interface(s) for the stores

2022-11-04 15:36 UTC, Mwpereira commented on client/src/store/tempData.jsx
>              uploadedOn: 'Nov-30-2022',
The server is expecting an EPOCH (time since EPOCH in a numerical format) - [https://www.epochconverter.com/](https://www.epochconverter.com/)

2022-11-04 15:36 UTC, Mwpereira commented on client/src/store/tempData.jsx
> +            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
Not expecting a url field.

export interface ImageModel {
    title: string,
    format: string,
    size: string,
    caption: string,
    tags: string[],
    categories: string[],
    owner: string,
    location: string,
    lastModifiedDateTime: number,
    uploadedDateTime: number,
}

2022-11-04 21:13 UTC, patel1643 commented on client/src/components/PhotoCard.tsx
> +interface PhotoCardProps {
- Ohh I just followed the figma design
- I agree I will make those changes in the next PR

2022-11-04 21:14 UTC, patel1643 commented on client/src/components/PhotoCard.tsx
> +    imageURL: string
bet bet bet

2022-11-04 21:15 UTC, patel1643 commented on client/src/components/PhotoCard.tsx
> +const DrawerImageInfo = (props: DrawerImageInfoProps) => {
nah it can't be re-used so I just made another component inside the file to keep it clean

2022-11-04 21:16 UTC, patel1643 commented on client/src/components/SideNavBar.tsx
> +        return await axios.get(URL + '/api/auth/logout');
sure I will make a service file for all the functions/api calls like these

2022-11-04 21:17 UTC, patel1643 commented on client/src/pages/Login.tsx
> +            if (response) {
yeah noted

2022-11-04 21:17 UTC, patel1643 commented on client/src/pages/Uploads.tsx
> +    const store = useStore();
ohh I already have I will just import it in this and assign as type Store

2022-11-04 21:18 UTC, patel1643 commented on client/src/store/tempData.jsx
> +            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
whoa nice thanks for the update I will add a new interface

2022-11-04 21:23 UTC, merged

2022-11-04 21:23 UTC, Mwpereira commented on client/src/store/tempData.jsx
> +            url: 'https://images.pexels.com/photos/884788/pexels-photo-884788.jpeg?cs=srgb&dl=pexels-david-besh-884788.jpg&fm=jpg',
These can be found under server/src/interfaces

2022-11-07 02:33 UTC, patel1643 commented on client/src/pages/Login.tsx
>              const response: any = await login(data.email, data.password);
I can't find this one bro

2022-11-07 02:44 UTC, patel1643 commented on client/src/store/tempData.jsx
>              uploadedOn: 'Nov-30-2022',
bet

2022-11-07 02:56 UTC, patel1643 commented on client/src/store/tempData.jsx
>              uploadedOn: 'Nov-30-2022',
also this is done on server right? if so I will just add a conversion method